export type ShopProduct = {
  id: string;
  name: string;
  category: "Vegetables" | "Fruits" | "Grains" | "Farm Tools" | "Seeds" | "Livestock" | "Pesticides" | "Dairy";
  price: number;
  originalPrice?: number | null;
  rating: number;
  reviewsCount: number;
  reviews?: number; // compat
  badge?: "Best Seller" | "Organic" | "New" | "Sale" | "Bulk Deal" | "Flash Deal" | "Anniversary Deal" | "" | null;
  image: string;
  brand: string;
  seller?: string; // compat
  stock: number;
  description: string;
  county: string;
  organic: boolean;
  verifiedSeller: boolean;
  unit: string;
  sellerScore: number; // Jumia seller score percentage (0-100)
  condition: "Fresh" | "Certified Organic" | "Bulk Available" | "Pre-Order";
};

export const shopProducts: ShopProduct[] = [
  {
    id: "1",
    name: "Sukuma Wiki (Kale) Fresh Bunch",
    brand: "Kamau Farms",
    seller: "Kamau Farms",
    price: 45,
    unit: "/bunch",
    category: "Vegetables",
    rating: 4.8,
    reviewsCount: 124,
    reviews: 124,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1628773822503-930a8589c313?w=400",
    stock: 120,
    description: "Crisp, nutrient-rich collard greens harvested at dawn. Grown organically in Kiambu volcanic soil, washed, and bundled ready for your kitchen.",
    county: "Kiambu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 85,
    condition: "Fresh"
  },
  {
    id: "2",
    name: "Organic Tomatoes Grade A",
    brand: "Wambui Organics",
    seller: "Wambui Organics",
    price: 120,
    originalPrice: 150,
    unit: "/kg",
    category: "Vegetables",
    rating: 4.6,
    reviewsCount: 89,
    reviews: 89,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=400",
    stock: 80,
    description: "Sun-ripened organic tomatoes with a rich, sweet flavor. Grown using zero chemical fertilizers in Kirinyaga County. Ideal for sauces and salads.",
    county: "Kirinyaga",
    organic: true,
    verifiedSeller: true,
    sellerScore: 90,
    condition: "Certified Organic"
  },
  {
    id: "3",
    name: "White Maize Flour 2kg Pack",
    brand: "Unga ya Baba",
    seller: "Unga ya Baba",
    price: 210,
    originalPrice: 250,
    unit: "/pack",
    category: "Grains",
    rating: 4.9,
    reviewsCount: 203,
    reviews: 203,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=400",
    stock: 250,
    description: "Premium stone-ground white maize meal. Sourced from high-quality Eldoret maize, sifted to perfection for traditional fluffy ugali.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 92,
    condition: "Bulk Available"
  },
  {
    id: "4",
    name: "Avocado Hass Premium",
    brand: "Nyandarua Fresh",
    seller: "Nyandarua Fresh",
    price: 30,
    originalPrice: null,
    unit: "/piece",
    category: "Fruits",
    rating: 4.7,
    reviewsCount: 156,
    reviews: 156,
    badge: null,
    image: "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400",
    stock: 180,
    description: "Butter-soft Hass avocados from Murang'a orchards. Rich in healthy fats with a creamy, nutty flavor profile.",
    county: "Murang'a",
    organic: true,
    verifiedSeller: true,
    sellerScore: 83,
    condition: "Fresh"
  },
  {
    id: "5",
    name: "Garden Hoe Long Handle Steel",
    brand: "AgroTools KE",
    seller: "AgroTools KE",
    price: 850,
    originalPrice: 1200,
    unit: "/unit",
    category: "Farm Tools",
    rating: 4.5,
    reviewsCount: 67,
    reviews: 67,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    stock: 45,
    description: "Forged high-carbon steel farm hoe fitted with a 1.5m lightweight hardwood handle. Designed for longevity and optimal weeding leverage.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 75,
    condition: "Pre-Order"
  },
  {
    id: "6",
    name: "Fresh Spinach Bunch",
    brand: "Rift Valley Greens",
    seller: "Rift Valley Greens",
    price: 35,
    originalPrice: null,
    unit: "/bunch",
    category: "Vegetables",
    rating: 4.8,
    reviewsCount: 91,
    reviews: 91,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
    stock: 110,
    description: "Lush, iron-rich spinach leaves cultivated using sustainable organic practices in Nakuru. Perfect for stews and green smoothies.",
    county: "Nakuru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 88,
    condition: "Fresh"
  },
  {
    id: "7",
    name: "Chia Seeds Organic 500g",
    brand: "Organic Africa",
    seller: "Organic Africa",
    price: 480,
    originalPrice: 600,
    unit: "/pack",
    category: "Seeds",
    rating: 4.6,
    reviewsCount: 45,
    reviews: 45,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1514690788374-6cbdf79b8c52?w=400",
    stock: 75,
    description: "Premium black chia seeds packed with omega-3 fatty acids, fiber, and protein. Triple-sorted and vacuum sealed for freshness.",
    county: "Meru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 78,
    condition: "Certified Organic"
  },
  {
    id: "8",
    name: "Pumpkin Medium Size",
    brand: "Mutura Farms",
    seller: "Mutura Farms",
    price: 95,
    originalPrice: null,
    unit: "/piece",
    category: "Vegetables",
    rating: 4.4,
    reviewsCount: 78,
    reviews: 78,
    badge: null,
    image: "https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=400",
    stock: 60,
    description: "Sweet, orange-fleshed pumpkins grown in Nyeri County. Highly nutritious and features an excellent storage shelf-life.",
    county: "Nyeri",
    organic: true,
    verifiedSeller: true,
    sellerScore: 65,
    condition: "Fresh"
  },
  {
    id: "9",
    name: "Layers Mash Premium 70kg Bag",
    brand: "Unga Feeds",
    seller: "Unga Feeds",
    price: 3650,
    originalPrice: 4200,
    unit: "/bag",
    category: "Livestock",
    rating: 4.7,
    reviewsCount: 112,
    reviews: 112,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
    stock: 35,
    description: "Complete nutrition mash for laying hens. Scientifically formulated with vitamins and calcium to maximize egg yield and shell hardness.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 82,
    condition: "Bulk Available"
  },
  {
    id: "10",
    name: "Knapsack Sprayer 16L Manual",
    brand: "Cooper Agri",
    seller: "Cooper Agri",
    price: 4500,
    originalPrice: 5500,
    unit: "/unit",
    category: "Farm Tools",
    rating: 4.5,
    reviewsCount: 34,
    reviews: 34,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    stock: 22,
    description: "Heavy-duty 16-liter agricultural knapsack sprayer. Features a padded harness, adjustable pressure nozzle, and dual-action pump.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 77,
    condition: "Pre-Order"
  },
  {
    id: "11",
    name: "DK 8031 Hybrid Maize Seed 2kg",
    brand: "Dekalb Kenya",
    seller: "Dekalb Kenya",
    price: 680,
    originalPrice: 800,
    unit: "/pack",
    category: "Seeds",
    rating: 4.9,
    reviewsCount: 287,
    reviews: 287,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    stock: 140,
    description: "Certified high-yield hybrid maize seeds. Drought-tolerant, disease-resistant, and ideal for medium-altitude farming zones.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "12",
    name: "Watermelon Sugar Baby Seeds",
    brand: "Simlaw Seeds",
    seller: "Simlaw Seeds",
    price: 320,
    originalPrice: null,
    unit: "/50g",
    category: "Seeds",
    rating: 4.6,
    reviewsCount: 93,
    reviews: 93,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400",
    stock: 90,
    description: "High purity sugar baby watermelon seeds. Fast maturing with exceptionally sweet and juicy yield characteristics.",
    county: "Kiambu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 86,
    condition: "Certified Organic"
  },
  // Extra 36 products to reach 48 products
  {
    id: "13",
    name: "Sweet Yellow Bananas Hand",
    brand: "Nyandarua Fresh",
    seller: "Nyandarua Fresh",
    price: 60,
    originalPrice: 80,
    unit: "/bunch",
    category: "Fruits",
    rating: 4.5,
    reviewsCount: 54,
    reviews: 54,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400",
    stock: 200,
    description: "Sun-ripened, naturally sweet yellow bananas grown pesticide-free in Murang'a County orchards.",
    county: "Murang'a",
    organic: true,
    verifiedSeller: true,
    sellerScore: 83,
    condition: "Fresh"
  },
  {
    id: "14",
    name: "Volcanic Head Green Cabbage",
    brand: "Kamau Farms",
    seller: "Kamau Farms",
    price: 80,
    originalPrice: null,
    unit: "/piece",
    category: "Vegetables",
    rating: 4.3,
    reviewsCount: 42,
    reviews: 42,
    badge: null,
    image: "https://images.unsplash.com/photo-1550411294-875307bcc77c?w=400",
    stock: 150,
    description: "Crunchy green cabbages grown in mineral-rich volcanic soils. High iron content and outstanding freshness.",
    county: "Kiambu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 85,
    condition: "Fresh"
  },
  {
    id: "15",
    name: "Sorghum Red Grains 5kg Bag",
    brand: "Unga ya Baba",
    seller: "Unga ya Baba",
    price: 450,
    originalPrice: 500,
    unit: "/bag",
    category: "Grains",
    rating: 4.7,
    reviewsCount: 31,
    reviews: 31,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=400",
    stock: 120,
    description: "Perfectly sun-dried and cleaned red sorghum grains. Ideal for brewing or healthy traditional porridges.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 92,
    condition: "Bulk Available"
  },
  {
    id: "16",
    name: "Red Onion Bulb Premium 1kg",
    brand: "Wambui Organics",
    seller: "Wambui Organics",
    price: 180,
    originalPrice: 220,
    unit: "/kg",
    category: "Vegetables",
    rating: 4.6,
    reviewsCount: 76,
    reviews: 76,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1618519764620-7403abdbfee9?w=400",
    stock: 95,
    description: "Strong aromatic red onions. Solid bulbs with high dry-matter content and excellent shelf-life storage.",
    county: "Kirinyaga",
    organic: true,
    verifiedSeller: true,
    sellerScore: 90,
    condition: "Certified Organic"
  },
  {
    id: "17",
    name: "Drip Irrigation Pipe Kit 100m",
    brand: "AgroTools KE",
    seller: "AgroTools KE",
    price: 4800,
    originalPrice: 5500,
    unit: "/unit",
    category: "Farm Tools",
    rating: 4.8,
    reviewsCount: 29,
    reviews: 29,
    badge: "Anniversary Deal",
    image: "https://images.unsplash.com/photo-1598902108854-10e335adac99?w=400",
    stock: 15,
    description: "Complete greenhouse/garden drip irrigation kit. UV resistant pipelines fitted with standard drippers.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 75,
    condition: "Pre-Order"
  },
  {
    id: "18",
    name: "Kienyeji Chicken Feed 50kg Bag",
    brand: "Unga Feeds",
    seller: "Unga Feeds",
    price: 2850,
    originalPrice: 3200,
    unit: "/bag",
    category: "Livestock",
    rating: 4.7,
    reviewsCount: 65,
    reviews: 65,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
    stock: 40,
    description: "Premium balanced feeds for free-range indigenous chickens. Promotes faster growth and excellent meat quality.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 82,
    condition: "Bulk Available"
  },
  {
    id: "19",
    name: "Dairy Cows Dairy Meal 50kg",
    brand: "Unga Feeds",
    seller: "Unga Feeds",
    price: 2450,
    originalPrice: 2800,
    unit: "/bag",
    category: "Livestock",
    rating: 4.5,
    reviewsCount: 52,
    reviews: 52,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
    stock: 50,
    description: "High-energy dairy concentrate formulated to boost milk yields and sustain cow fertility.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 82,
    condition: "Bulk Available"
  },
  {
    id: "20",
    name: "Machakos Apple Mangoes Box",
    brand: "Nyandarua Fresh",
    seller: "Nyandarua Fresh",
    price: 350,
    originalPrice: 420,
    unit: "/box",
    category: "Fruits",
    rating: 4.8,
    reviewsCount: 88,
    reviews: 88,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400",
    stock: 65,
    description: "Fleshy, fiberless Apple Mangoes sourced from eastern orchards. Sweet, juicy, and sun-ripened.",
    county: "Machakos",
    organic: true,
    verifiedSeller: true,
    sellerScore: 83,
    condition: "Fresh"
  },
  {
    id: "21",
    name: "Irish Potatoes Grade A 50kg",
    brand: "Kamau Farms",
    seller: "Kamau Farms",
    price: 2200,
    originalPrice: null,
    unit: "/bag",
    category: "Vegetables",
    rating: 4.4,
    reviewsCount: 47,
    reviews: 47,
    badge: null,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    stock: 30,
    description: "Red-skin Irish potatoes hand-sorted. Ideal for baking, frying, or boiling. Straight from farmers.",
    county: "Kiambu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 85,
    condition: "Bulk Available"
  },
  {
    id: "22",
    name: "Certified Sunflower Seeds 2kg",
    brand: "Simlaw Seeds",
    seller: "Simlaw Seeds",
    price: 950,
    originalPrice: 1100,
    unit: "/pack",
    category: "Seeds",
    rating: 4.6,
    reviewsCount: 23,
    reviews: 23,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1595971291494-0120b7274020?w=400",
    stock: 40,
    description: "Certified hybrid sunflower seeds with high oil concentration content. Fast maturity rates.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 86,
    condition: "Certified Organic"
  },
  {
    id: "23",
    name: "Sorghum Seeds Grade K6 2kg",
    brand: "Dekalb Kenya",
    seller: "Dekalb Kenya",
    price: 580,
    originalPrice: null,
    unit: "/pack",
    category: "Seeds",
    rating: 4.7,
    reviewsCount: 38,
    reviews: 38,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    stock: 80,
    description: "Drought resistant sorghum seeds suitable for dry areas. Heavy grains and high yields.",
    county: "Uasin Gishu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Certified Organic"
  },
  {
    id: "24",
    name: "Copper Fungicide Powder 1kg",
    brand: "Cooper Agri",
    seller: "Cooper Agri",
    price: 1400,
    originalPrice: 1700,
    unit: "/unit",
    category: "Pesticides",
    rating: 4.5,
    reviewsCount: 19,
    reviews: 19,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    stock: 35,
    description: "Broad spectrum copper-based fungicide to control leaf spot, rust, and blight diseases.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 77,
    condition: "Pre-Order"
  },
  {
    id: "25",
    name: "Fresh Whole Milk 1 Litre",
    brand: "Rift Valley Greens",
    seller: "Rift Valley Greens",
    price: 90,
    originalPrice: 100,
    unit: "/packet",
    category: "Dairy",
    rating: 4.9,
    reviewsCount: 143,
    reviews: 143,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    stock: 300,
    description: "Freshly pasteurized whole milk from free-grazing Holstein-Friesian herds in Nakuru County.",
    county: "Nakuru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 88,
    condition: "Fresh"
  },
  {
    id: "26",
    name: "Natural Butter Ghee 500g",
    brand: "Rift Valley Greens",
    seller: "Rift Valley Greens",
    price: 550,
    originalPrice: null,
    unit: "/jar",
    category: "Dairy",
    rating: 4.8,
    reviewsCount: 56,
    reviews: 56,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    stock: 60,
    description: "Pure clarified butter ghee. Rich aroma, perfect for cooking traditional dishes.",
    county: "Nakuru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 88,
    condition: "Certified Organic"
  },
  {
    id: "27",
    name: "Athi River Grass Hay Bales",
    brand: "Mutura Farms",
    seller: "Mutura Farms",
    price: 250,
    originalPrice: 300,
    unit: "/bale",
    category: "Livestock",
    rating: 4.4,
    reviewsCount: 39,
    reviews: 39,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
    stock: 200,
    description: "Premium sun-cured Rhodes grass hay bales. High dry matter and fiber content for beef and dairy stock.",
    county: "Nyeri",
    organic: true,
    verifiedSeller: true,
    sellerScore: 65,
    condition: "Bulk Available"
  },
  {
    id: "28",
    name: "Organic Honey Pure Raw 1kg",
    brand: "Organic Africa",
    seller: "Organic Africa",
    price: 850,
    originalPrice: 1000,
    unit: "/bottle",
    category: "Dairy",
    rating: 4.9,
    reviewsCount: 110,
    reviews: 110,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400",
    stock: 90,
    description: "100% natural, unfiltered wild forest honey. Sourced ethically from traditional hives in Baringo.",
    county: "Baringo",
    organic: true,
    verifiedSeller: true,
    sellerScore: 78,
    condition: "Certified Organic"
  },
  {
    id: "29",
    name: "Pruning Shears Bypass Steel",
    brand: "AgroTools KE",
    seller: "AgroTools KE",
    price: 750,
    originalPrice: null,
    unit: "/unit",
    category: "Farm Tools",
    rating: 4.6,
    reviewsCount: 41,
    reviews: 41,
    badge: null,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    stock: 80,
    description: "Ergonomic rust-resistant stainless steel bypass pruner for precise branch trimming.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 75,
    condition: "Pre-Order"
  },
  {
    id: "30",
    name: "Organic Beetroot Bunch Fresh",
    brand: "Wambui Organics",
    seller: "Wambui Organics",
    price: 110,
    originalPrice: 130,
    unit: "/kg",
    category: "Vegetables",
    rating: 4.7,
    reviewsCount: 32,
    reviews: 32,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1587334206574-307eb13b1b48?w=400",
    stock: 70,
    description: "Freshly pulled organic beetroot bulbs. Rich crimson color and earthy flavor.",
    county: "Kirinyaga",
    organic: true,
    verifiedSeller: true,
    sellerScore: 90,
    condition: "Fresh"
  },
  {
    id: "31",
    name: "Sweet Potato Red Skin 10kg",
    brand: "Kamau Farms",
    seller: "Kamau Farms",
    price: 650,
    originalPrice: 750,
    unit: "/sack",
    category: "Vegetables",
    rating: 4.5,
    reviewsCount: 49,
    reviews: 49,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=400",
    stock: 50,
    description: "Nutritious orange-fleshed sweet potatoes. Sourced fresh from rich soils.",
    county: "Kiambu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 85,
    condition: "Bulk Available"
  },
  {
    id: "32",
    name: "Organic Butternut Squash",
    brand: "Wambui Organics",
    seller: "Wambui Organics",
    price: 90,
    originalPrice: null,
    unit: "/piece",
    category: "Vegetables",
    rating: 4.5,
    reviewsCount: 56,
    reviews: 56,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=400",
    stock: 90,
    description: "Creamy, naturally sweet butternut squashes. Organically certified and harvested fresh.",
    county: "Kirinyaga",
    organic: true,
    verifiedSeller: true,
    sellerScore: 90,
    condition: "Fresh"
  },
  {
    id: "33",
    name: "Premium Rice Pishori 5kg Bag",
    brand: "Unga ya Baba",
    seller: "Unga ya Baba",
    price: 950,
    originalPrice: 1100,
    unit: "/bag",
    category: "Grains",
    rating: 4.9,
    reviewsCount: 167,
    reviews: 167,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    stock: 120,
    description: "Aromatic long-grain Pishori rice from Mwea paddies. Pure, unblended, clean grain polish.",
    county: "Kirinyaga",
    organic: false,
    verifiedSeller: true,
    sellerScore: 92,
    condition: "Bulk Available"
  },
  {
    id: "34",
    name: "Pearl Millet Seeds 2kg Pack",
    brand: "Simlaw Seeds",
    seller: "Simlaw Seeds",
    price: 360,
    originalPrice: 420,
    unit: "/pack",
    category: "Seeds",
    rating: 4.7,
    reviewsCount: 39,
    reviews: 39,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    stock: 90,
    description: "Certified pearl millet seeds for drought zones. Premium bird and poultry feed grain seed stock.",
    county: "Kiambu",
    organic: true,
    verifiedSeller: true,
    sellerScore: 86,
    condition: "Certified Organic"
  },
  {
    id: "35",
    name: "Insecticide Actellic Gold 1L",
    brand: "Cooper Agri",
    seller: "Cooper Agri",
    price: 1900,
    originalPrice: null,
    unit: "/unit",
    category: "Pesticides",
    rating: 4.6,
    reviewsCount: 47,
    reviews: 47,
    badge: null,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    stock: 60,
    description: "Long-term grain protectant insecticide for stored crop products. Prevents weevils.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 77,
    condition: "Pre-Order"
  },
  {
    id: "36",
    name: "NPK Fertilizer 17:17:17 50kg",
    brand: "Cooper Agri",
    seller: "Cooper Agri",
    price: 3200,
    originalPrice: 3800,
    unit: "/bag",
    category: "Pesticides",
    rating: 4.8,
    reviewsCount: 92,
    reviews: 92,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
    stock: 45,
    description: "Balanced compound NPK fertilizer. Ideal for planting and root structure development.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 77,
    condition: "Bulk Available"
  },
  {
    id: "37",
    name: "Grafted Passion Fruit Seedlings",
    brand: "Organic Africa",
    seller: "Organic Africa",
    price: 150,
    originalPrice: 180,
    unit: "/seedling",
    category: "Seeds",
    rating: 4.7,
    reviewsCount: 52,
    reviews: 52,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1595971291494-0120b7274020?w=400",
    stock: 120,
    description: "Disease resistant purple passion fruit seedlings grafted with strong yellow passion rootstocks.",
    county: "Meru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 78,
    condition: "Certified Organic"
  },
  {
    id: "38",
    name: "Spade Solid Steel Spade",
    brand: "AgroTools KE",
    seller: "AgroTools KE",
    price: 950,
    originalPrice: 1200,
    unit: "/unit",
    category: "Farm Tools",
    rating: 4.5,
    reviewsCount: 33,
    reviews: 33,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1598902108854-10e335adac99?w=400",
    stock: 30,
    description: "One-piece forged steel garden spade. Heavy duty spade blade for tough soil digging operations.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 75,
    condition: "Pre-Order"
  },
  {
    id: "39",
    name: "Fresh Strawberry Box 250g",
    brand: "Nyandarua Fresh",
    seller: "Nyandarua Fresh",
    price: 150,
    originalPrice: null,
    unit: "/punnet",
    category: "Fruits",
    rating: 4.8,
    reviewsCount: 42,
    reviews: 42,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400",
    stock: 80,
    description: "Luscious juicy strawberries grown under drip irrigation. Packaged fresh in recycled punnets.",
    county: "Murang'a",
    organic: true,
    verifiedSeller: true,
    sellerScore: 83,
    condition: "Fresh"
  },
  {
    id: "40",
    name: "Organic Red Plums 1kg Pack",
    brand: "Nyandarua Fresh",
    seller: "Nyandarua Fresh",
    price: 250,
    originalPrice: 300,
    unit: "/kg",
    category: "Fruits",
    rating: 4.6,
    reviewsCount: 29,
    reviews: 29,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=400",
    stock: 60,
    description: "Sweet and tangy red plums. Handpicked from organic tree groves in central highlands.",
    county: "Murang'a",
    organic: true,
    verifiedSeller: true,
    sellerScore: 83,
    condition: "Fresh"
  },
  {
    id: "41",
    name: "Certified Seed Potatoes 50kg",
    brand: "Dekalb Kenya",
    seller: "Dekalb Kenya",
    price: 3500,
    originalPrice: 4000,
    unit: "/bag",
    category: "Seeds",
    rating: 4.8,
    reviewsCount: 71,
    reviews: 71,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    stock: 25,
    description: "Certified Shangi seed potatoes. High yields and resistant to early potato blights.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Bulk Available"
  },
  {
    id: "42",
    name: "Watermelon Seed F1 Hybrid 100g",
    brand: "Simlaw Seeds",
    seller: "Simlaw Seeds",
    price: 1800,
    originalPrice: null,
    unit: "/pack",
    category: "Seeds",
    rating: 4.9,
    reviewsCount: 110,
    reviews: 110,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400",
    stock: 50,
    description: "High-yield hybrid watermelon seeds. Super sweet fruits with thick rind for shipping travel.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 86,
    condition: "Certified Organic"
  },
  {
    id: "43",
    name: "Manual Maize Sheller Machine",
    brand: "AgroTools KE",
    seller: "AgroTools KE",
    price: 3500,
    originalPrice: 4200,
    unit: "/unit",
    category: "Farm Tools",
    rating: 4.7,
    reviewsCount: 22,
    reviews: 22,
    badge: "Flash Deal",
    image: "https://images.unsplash.com/photo-1598902108854-10e335adac99?w=400",
    stock: 15,
    description: "Hand-cranked heavy cast iron maize sheller. Easily mounted to tables or posts for crop processing.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 75,
    condition: "Pre-Order"
  },
  {
    id: "44",
    name: "Cow Milk Yoghurt Strawberry 5L",
    brand: "Rift Valley Greens",
    seller: "Rift Valley Greens",
    price: 750,
    originalPrice: 900,
    unit: "/jerrycan",
    category: "Dairy",
    rating: 4.8,
    reviewsCount: 89,
    reviews: 89,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    stock: 40,
    description: "Thick, creamy strawberry yoghurt. Prepared using pure pasture milk and real strawberry pulps.",
    county: "Nakuru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 88,
    condition: "Bulk Available"
  },
  {
    id: "45",
    name: "DAP Fertilizer Planting 50kg",
    brand: "Cooper Agri",
    seller: "Cooper Agri",
    price: 3500,
    originalPrice: 4000,
    unit: "/bag",
    category: "Pesticides",
    rating: 4.8,
    reviewsCount: 154,
    reviews: 154,
    badge: "Bulk Deal",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
    stock: 60,
    description: "High-grade Diammonium Phosphate planting fertilizer. Excellent nitrogen and phosphorus crop boost.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 77,
    condition: "Bulk Available"
  },
  {
    id: "46",
    name: "Organic Red Capsicum Box 5kg",
    brand: "Wambui Organics",
    seller: "Wambui Organics",
    price: 400,
    originalPrice: 500,
    unit: "/box",
    category: "Vegetables",
    rating: 4.7,
    reviewsCount: 33,
    reviews: 33,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1563565312-233306d6cf23?w=400",
    stock: 45,
    description: "Grade A organic red bell peppers. Crispy, thick-fleshed sweet fruits for salad seasoning.",
    county: "Kirinyaga",
    organic: true,
    verifiedSeller: true,
    sellerScore: 90,
    condition: "Fresh"
  },
  {
    id: "47",
    name: "Grafted Avocado Seedlings",
    brand: "Organic Africa",
    seller: "Organic Africa",
    price: 180,
    originalPrice: 220,
    unit: "/seedling",
    category: "Seeds",
    rating: 4.9,
    reviewsCount: 78,
    reviews: 78,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1595971291494-0120b7274020?w=400",
    stock: 150,
    description: "High-grade grafted Hass avocado seedlings. Quick maturity and ready to transplant.",
    county: "Meru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 78,
    condition: "Certified Organic"
  },
  {
    id: "48",
    name: "Hay Forage Seeds Mix 5kg",
    brand: "Dekalb Kenya",
    seller: "Dekalb Kenya",
    price: 1200,
    originalPrice: null,
    unit: "/pack",
    category: "Seeds",
    rating: 4.6,
    reviewsCount: 22,
    reviews: 22,
    badge: null,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    stock: 90,
    description: "High nutrition pasture grass seeds mix (Rhodes, Boma, Lucerne). Promotes lush forage cover.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Certified Organic"
  }
];

export const shopCategories = [
  { id: "All", label: "All Products", icon: "📦" },
  { id: "Vegetables", label: "Vegetables & Greens", icon: "🥬" },
  { id: "Fruits", label: "Fruits", icon: "🍎" },
  { id: "Grains", label: "Grains & Cereals", icon: "🌾" },
  { id: "Seeds", label: "Seeds & Seedlings", icon: "🌱" },
  { id: "Livestock", label: "Livestock Feeds", icon: "🐄" },
  { id: "Farm Tools", label: "Farm Tools & Equipment", icon: "🚜" },
  { id: "Organic", label: "Organic Products", icon: "🌿" },
  { id: "Pesticides", label: "Pesticides & Fertilizers", icon: "🧪" },
  { id: "Dairy", label: "Dairy Products", icon: "🥛" }
];

export const shopCounties = [
  "All",
  "Kiambu",
  "Kirinyaga",
  "Uasin Gishu",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Meru",
  "Nyeri",
  "Machakos",
  "Baringo"
];

export const trustedSellers = [
  { name: "Kamau Farms", location: "Kiambu County", rating: 4.9, sales: "1,200+ orders", avatar: "🥬" },
  { name: "Wambui Organics", location: "Kirinyaga County", rating: 4.8, sales: "850+ orders", avatar: "🍅" },
  { name: "Rift Valley Greens", location: "Nakuru County", rating: 4.9, sales: "2,100+ orders", avatar: "🌿" },
  { name: "Organic Africa", location: "Meru County", rating: 4.7, sales: "640+ orders", avatar: "🌱" },
  { name: "Nyandarua Fresh", location: "Murang'a County", rating: 4.8, sales: "930+ orders", avatar: "🥑" },
  { name: "AgroTools KE", location: "Nairobi County", rating: 4.6, sales: "540+ orders", avatar: "🛠️" },
  { name: "Unga ya Baba", location: "Uasin Gishu County", rating: 4.9, sales: "3,100+ orders", avatar: "🌽" },
  { name: "Cooper Agri", location: "Nairobi County", rating: 4.7, sales: "720+ orders", avatar: "🧪" }
];
