export type ProductSizeOption = {
  name: string;
  price: number;
  originalPrice?: number | null;
  unit: string;
};

export type ShopProduct = {
  id: string;
  name: string;
  category: string;
  shopType?: string;      // "Agrovet" | "Specialist Shop" | "For Retailers"
  field?: string;         // "Crop Production" | "Fertilizers" | "Animal Production" | "Public Health & Sanitation" | "Farm tools, Implements & Machinery"
  subcategory?: string;
  price: number;
  originalPrice?: number | null;
  rating: number;
  reviewsCount: number;
  reviews?: number;
  badge?: "Best Seller" | "Organic" | "New" | "Sale" | "Bulk Deal" | "Flash Deal" | "Anniversary deal" | "" | null;
  image: string;
  brand: string;
  seller?: string;
  stock: number;
  description: string;
  county: string;
  organic: boolean;
  verifiedSeller: boolean;
  unit: string;
  sellerScore: number;
  condition: "Fresh" | "Certified Organic" | "Bulk Available" | "Pre-Order";
  sizes?: ProductSizeOption[];
};

export const shopProducts: ShopProduct[] = [
  // --- AGROVET -> CROP PRODUCTION -> PESTICIDES ---
  {
    id: "k1",
    name: "Kirgit Ridomil Fungicide",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1200,
    originalPrice: 1500,
    unit: "/kg",
    category: "Pesticides",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Fungicides",
    rating: 4.8,
    reviewsCount: 45,
    reviews: 45,
    badge: "Anniversary deal",
    image: "https://images.unsplash.com/photo-1563514220-ea97928b4988?w=400",
    stock: 80,
    description: "Premium preventive fungicide for control of early and late blight in potatoes, tomatoes, and grapes.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh",
    sizes: [
      { name: "250g", price: 400, originalPrice: 500, unit: "250g" },
      { name: "500g", price: 700, originalPrice: 900, unit: "500g" },
      { name: "1kg", price: 1200, originalPrice: 1500, unit: "kg" }
    ]
  },
  {
    id: "k2",
    name: "Kirgit Actara Insecticide",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 950,
    originalPrice: 1100,
    unit: "/50g",
    category: "Pesticides",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Insecticides",
    rating: 4.7,
    reviewsCount: 32,
    reviews: 32,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400",
    stock: 120,
    description: "Highly effective systemic insecticide for controlling aphids, whiteflies, and thrips in vegetable crops.",
    county: "Kirinyaga",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh",
    sizes: [
      { name: "50g", price: 950, originalPrice: 1100, unit: "50g" },
      { name: "250g", price: 4200, originalPrice: 4800, unit: "250g" }
    ]
  },
  {
    id: "k3",
    name: "Kirgit Roundup Herbicide",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1500,
    originalPrice: 1800,
    unit: "/Ltr",
    category: "Pesticides",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Herbicides",
    rating: 4.6,
    reviewsCount: 58,
    reviews: 58,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400",
    stock: 90,
    description: "Non-selective systemic herbicide for effective weed control during land preparation.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Bulk Available",
    sizes: [
      { name: "500ml", price: 900, originalPrice: 1050, unit: "500ml" },
      { name: "1L", price: 1500, originalPrice: 1800, unit: "Ltr" },
      { name: "5L", price: 7000, originalPrice: 8200, unit: "5L" }
    ]
  },
  {
    id: "k4",
    name: "Kirgit Nemacur Nematicide",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 2800,
    originalPrice: 3200,
    unit: "/kg",
    category: "Pesticides",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Nematicides",
    rating: 4.9,
    reviewsCount: 14,
    reviews: 14,
    badge: "New",
    image: "https://images.unsplash.com/photo-1463171359079-3d9996683be2?w=400",
    stock: 35,
    description: "Granular nematicide for the control of root-knot nematodes in tobacco, bananas, and flowers.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "k5",
    name: "Kirgit Storm Rodenticide",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 450,
    originalPrice: null,
    unit: "/100g",
    category: "Pesticides",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Rodenticides",
    rating: 4.5,
    reviewsCount: 22,
    reviews: 22,
    badge: null,
    image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400",
    stock: 200,
    description: "Highly palatable wax block rodenticide bait for controlling rats and mice in fields and stores.",
    county: "Nairobi",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },

  // --- AGROVET -> CROP PRODUCTION -> FOLIAR FERTILIZER ---
  {
    id: "k6",
    name: "Kirgit Org-Grow Foliar",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1800,
    originalPrice: 2200,
    unit: "/Ltr",
    category: "Foliar Fertilizer",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Organic",
    rating: 4.9,
    reviewsCount: 39,
    reviews: 39,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    stock: 150,
    description: "100% natural organic liquid foliar fertilizer enriched with humic acids and seaweed extracts.",
    county: "Murang'a",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Certified Organic"
  },
  {
    id: "k7",
    name: "Kirgit NPK 20-20-20 Compound Foliar",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1600,
    originalPrice: 1900,
    unit: "/kg",
    category: "Foliar Fertilizer",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Compound foliar",
    rating: 4.7,
    reviewsCount: 41,
    reviews: 41,
    badge: "Anniversary deal",
    image: "https://images.unsplash.com/photo-1506543730435-e2c6f45540e2?w=400",
    stock: 110,
    description: "Balanced compound foliar fertilizer for vegetative, flowering, and fruiting crop stages.",
    county: "Nyeri",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },

  // --- AGROVET -> CROP PRODUCTION -> GROWTH CATALYSTS & BIOSTIMULANTS ---
  {
    id: "k8",
    name: "Kirgit Auxin Rooting Catalyst",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 750,
    originalPrice: null,
    unit: "/100ml",
    category: "Growth Catalysts",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Hormones",
    rating: 4.8,
    reviewsCount: 19,
    reviews: 19,
    badge: "New",
    image: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=400",
    stock: 75,
    description: "Hormone growth catalyst for stimulating fast and strong root development in cuttings.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "k9",
    name: "Kirgit Kelp Seaweed Biostimulant",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 2100,
    originalPrice: 2500,
    unit: "/Ltr",
    category: "Biostimulants",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Biostimulants",
    rating: 4.9,
    reviewsCount: 26,
    reviews: 26,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=400",
    stock: 60,
    description: "Premium biostimulant that triggers natural immunity and heat/drought resistance in plants.",
    county: "Kirinyaga",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Certified Organic"
  },

  // --- AGROVET -> CROP PRODUCTION -> SEEDS & SEEDLINGS ---
  {
    id: "k10",
    name: "Kirgit Hybrid Maize H614 Seeds",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 450,
    originalPrice: 500,
    unit: "/2kg",
    category: "Seeds & Seedlings",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Seeds",
    rating: 4.9,
    reviewsCount: 132,
    reviews: 132,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=400",
    stock: 500,
    description: "High-yielding hybrid maize seed certified for medium to high altitude regions.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Bulk Available"
  },
  {
    id: "k11",
    name: "Kirgit Pinot Red Onion Seeds",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 800,
    originalPrice: 950,
    unit: "/100g",
    category: "Seeds & Seedlings",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Seeds",
    rating: 4.8,
    reviewsCount: 78,
    reviews: 78,
    badge: "Anniversary deal",
    image: "https://images.unsplash.com/photo-1608797178974-15b35a61d121?w=400",
    stock: 150,
    description: "High germination rate red onion seeds producing deep red medium-to-large sized bulbs.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "k12",
    name: "Kirgit Grafted Hass Avocado Seedling",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 150,
    originalPrice: null,
    unit: "/seedling",
    category: "Seeds & Seedlings",
    shopType: "Agrovet",
    field: "Crop Production",
    subcategory: "Seedlings",
    rating: 4.9,
    reviewsCount: 94,
    reviews: 94,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400",
    stock: 300,
    description: "Grafted Hass avocado tree seedling, early maturing and highly disease resistant.",
    county: "Murang'a",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },

  // --- AGROVET -> FERTILIZERS ---
  {
    id: "k13",
    name: "Kirgit DAP Planting Fertilizer",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 3200,
    originalPrice: 3500,
    unit: "/50kg",
    category: "Planting",
    shopType: "Agrovet",
    field: "Fertilizers",
    subcategory: "Planting",
    rating: 4.9,
    reviewsCount: 165,
    reviews: 165,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?w=400",
    stock: 120,
    description: "High phosphorus planting fertilizer (18:46:0) for robust early root growth in maize, potatoes, and wheat.",
    county: "Uasin Gishu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Bulk Available",
    sizes: [
      { name: "10kg", price: 800, originalPrice: 950, unit: "10kg" },
      { name: "25kg", price: 1750, originalPrice: 1950, unit: "25kg" },
      { name: "50kg", price: 3200, originalPrice: 3500, unit: "50kg" }
    ]
  },
  {
    id: "k14",
    name: "Kirgit CAN Top Dressing Fertilizer",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 2900,
    originalPrice: null,
    unit: "/50kg",
    category: "Top Dressing",
    shopType: "Agrovet",
    field: "Fertilizers",
    subcategory: "Top Dressing",
    rating: 4.8,
    reviewsCount: 110,
    reviews: 110,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    stock: 80,
    description: "Calcium Ammonium Nitrate fertilizer, perfect for top dressing to boost green foliage growth.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Bulk Available"
  },
  {
    id: "k15",
    name: "Kirgit Sheep Manure Organic Fertilizer",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 400,
    originalPrice: 450,
    unit: "/25kg",
    category: "Organic fertilizer",
    shopType: "Agrovet",
    field: "Fertilizers",
    subcategory: "Manure",
    rating: 4.7,
    reviewsCount: 55,
    reviews: 55,
    badge: "Organic",
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=400",
    stock: 400,
    description: "Decomposed sheep manure organic fertilizer, rich in organic matter to build soil health.",
    county: "Nakuru",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Certified Organic"
  },

  // --- AGROVET -> ANIMAL PRODUCTION -> ANIMAL FEEDS ---
  {
    id: "k16",
    name: "Kirgit Dairy Meal High-Yield",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 2150,
    originalPrice: 2400,
    unit: "/50kg",
    category: "Animal Feeds",
    shopType: "Agrovet",
    field: "Animal Production",
    subcategory: "Dairy",
    rating: 4.8,
    reviewsCount: 88,
    reviews: 88,
    badge: "Anniversary deal",
    image: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=400",
    stock: 150,
    description: "Premium dairy meal concentrate formulated to maximize milk yields and maintain herd condition.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Bulk Available",
    sizes: [
      { name: "10kg", price: 550, originalPrice: 650, unit: "10kg" },
      { name: "25kg", price: 1200, originalPrice: 1350, unit: "25kg" },
      { name: "50kg", price: 2150, originalPrice: 2400, unit: "50kg" }
    ]
  },
  {
    id: "k17",
    name: "Kirgit Tilapia Floating Pellets",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1800,
    originalPrice: null,
    unit: "/20kg",
    category: "Animal Feeds",
    shopType: "Agrovet",
    field: "Animal Production",
    subcategory: "Fish",
    rating: 4.6,
    reviewsCount: 15,
    reviews: 15,
    badge: "New",
    image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400",
    stock: 60,
    description: "Floating fish feed pellets with high crude protein content for rapid growth of tilapia fingerlings.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },

  // --- AGROVET -> ANIMAL PRODUCTION -> ANIMAL PESTICIDES & SUPPLS ---
  {
    id: "k18",
    name: "Kirgit Triatix Tick Spray Acaricide",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1200,
    originalPrice: 1350,
    unit: "/100ml",
    category: "Animal pesticides",
    shopType: "Agrovet",
    field: "Animal Production",
    subcategory: "Acaricides",
    rating: 4.9,
    reviewsCount: 74,
    reviews: 74,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=400",
    stock: 180,
    description: "Potent acaricide spray for total control of ticks, mites, and lice on cattle and sheep.",
    county: "Nyeri",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "k19",
    name: "Kirgit Maclik Mineral Salt Lick",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 550,
    originalPrice: null,
    unit: "/2kg",
    category: "Supplements",
    shopType: "Agrovet",
    field: "Animal Production",
    subcategory: "Salts",
    rating: 4.8,
    reviewsCount: 62,
    reviews: 62,
    badge: null,
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400",
    stock: 250,
    description: "Essential mineral salt lick block to satisfy sodium and calcium needs in dairy animals.",
    county: "Machakos",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },

  // --- AGROVET -> PUBLIC HEALTH & SANITATION ---
  {
    id: "k20",
    name: "Kirgit Pit Latrine Bio-Digester",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 950,
    originalPrice: 1200,
    unit: "/pack",
    category: "Sewage & Excreta",
    shopType: "Agrovet",
    field: "Public Health & Sanitation",
    subcategory: "Sewage & Excreta",
    rating: 4.8,
    reviewsCount: 33,
    reviews: 33,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    stock: 140,
    description: "Highly active bacterial blend to digest waste, reduce pit levels, and eliminate bad odors.",
    county: "Nairobi",
    organic: true,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },

  // --- AGROVET -> FARM TOOLS, IMPLEMENTS & MACHINERY ---
  {
    id: "k21",
    name: "Kirgit Heavy Duty Farm Jembe",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 450,
    originalPrice: null,
    unit: "/piece",
    category: "Tools",
    shopType: "Agrovet",
    field: "Farm tools, Implements & Machinery",
    subcategory: "Tools",
    rating: 4.7,
    reviewsCount: 89,
    reviews: 89,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=400",
    stock: 100,
    description: "Forged carbon steel hoe head (Jembe) for rigorous digging and weeding operations.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "k22",
    name: "Kirgit Portable Maize Thresher",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 85000,
    originalPrice: 95000,
    unit: "/unit",
    category: "Machinery",
    shopType: "Agrovet",
    field: "Farm tools, Implements & Machinery",
    subcategory: "Machinery",
    rating: 4.9,
    reviewsCount: 9,
    reviews: 9,
    badge: "New",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400",
    stock: 5,
    description: "Engine-powered high output mobile maize sheller. Cleanly separates grains with minimal cob breakage.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Pre-Order"
  },

  // --- SPECIALIST SHOP -> DOMESTIC ANIMAL PHARMACY ---
  {
    id: "k23",
    name: "Kirgit Veterinary Oxytetracycline OTC 20%",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 1250,
    originalPrice: 1450,
    unit: "/100ml",
    category: "Domestic Animal pharmacy",
    shopType: "Specialist Shop",
    field: "Domestic Animal pharmacy",
    subcategory: "Antimicrobials",
    rating: 4.9,
    reviewsCount: 51,
    reviews: 51,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    stock: 90,
    description: "Broad spectrum antibiotic injection for treating bacterial infections in cows, sheep, and goats.",
    county: "Nakuru",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  },
  {
    id: "k24",
    name: "Kirgit Amprolium Coccidiostats Powder",
    brand: "Kirgit Agriculture",
    seller: "Kirgit Agriculture",
    price: 950,
    originalPrice: null,
    unit: "/100g",
    category: "Domestic Animal pharmacy",
    shopType: "Specialist Shop",
    field: "Domestic Animal pharmacy",
    subcategory: "Coccidiostats",
    rating: 4.8,
    reviewsCount: 42,
    reviews: 42,
    badge: "New",
    image: "https://images.unsplash.com/photo-1604186837056-8e7c2867b6f2?w=400",
    stock: 120,
    description: "Water soluble coccidiostat powder for the prevention and treatment of coccidiosis in poultry.",
    county: "Kiambu",
    organic: false,
    verifiedSeller: true,
    sellerScore: 95,
    condition: "Fresh"
  }
];

export const shopCategories = [
  { id: "All", label: "All Products", icon: "📦" },
  
  // Agrovet -> Crop Production
  { id: "Pesticides", label: "Pesticides", icon: "🧪" },
  { id: "Foliar Fertilizer", label: "Foliar Fertilizer", icon: "🍃" },
  { id: "Growth Catalysts", label: "Growth Catalysts", icon: "📈" },
  { id: "Biostimulants", label: "Biostimulants", icon: "⚡" },
  { id: "Post Harvest", label: "Post Harvest", icon: "📦" },
  { id: "Seeds & Seedlings", label: "Seeds & Seedlings", icon: "🌱" },
  
  // Agrovet -> Fertilizers
  { id: "Planting", label: "Planting Fertilizers", icon: "🕳️" },
  { id: "Top Dressing", label: "Top Dressing Fertilizers", icon: "🍚" },
  { id: "Blended", label: "Blended Fertilizers", icon: "🔀" },
  { id: "Specialized Fertilizers", label: "Specialized Fertilizers", icon: "✨" },
  { id: "Organic fertilizer", label: "Organic Fertilizer", icon: "💩" },
  
  // Agrovet -> Animal Production
  { id: "Animal Feeds", label: "Animal Feeds", icon: "🐄" },
  { id: "Animal pesticides", label: "Animal Pesticides", icon: "🪰" },
  { id: "Supplements", label: "Supplements & Additives", icon: "💊" },
  
  // Agrovet -> Public Health & Sanitation
  { id: "Water treatment", label: "Water Treatment", icon: "💧" },
  { id: "Sewage & Excreta", label: "Sewage & Excreta", icon: "🚽" },
  { id: "Environmental", label: "Environmental Sanitation", icon: "🧹" },
  
  // Agrovet -> Farm tools, Implements & Machinery
  { id: "Tools", label: "Farm Tools", icon: "🔨" },
  { id: "Implements", label: "Farm Implements", icon: "🚜" },
  { id: "Machinery", label: "Farm Machinery", icon: "⚙️" },
  
  // Specialist Shop
  { id: "Domestic Animal pharmacy", label: "Domestic Animal Pharmacy", icon: "🏥" }
];

export const shopCounties = [
  "All",
  "Kiambu",
  "Kirinyaga",
  "Uasin Gishu",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Meru",
  "Nyeri",
  "Machakos",
  "Baringo"
];

export const trustedSellers = [
  { name: "Kirgit Agriculture", location: "Nakuru County", rating: 4.9, sales: "5,000+ orders", avatar: "🐂" }
];
